baseURL = 'https://IamAlch3mist.github.io/'
languageCode = 'en-us'
title = 'IamAlch3mist blogs'

theme = 'terminal'
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "purple"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[[menu.main]]
name = "`whoami`"
url = "/about/"
weight = 10
